# Generated by Django 4.2.6 on 2023-10-29 23:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('psesyn_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='home',
            name='publication_date',
        ),
    ]
