# Generated by Django 4.2.6 on 2023-11-01 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='publication_date',
        ),
        migrations.AddField(
            model_name='news',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='news/'),
        ),
        migrations.AddField(
            model_name='news',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
