# Generated by Django 4.2.6 on 2023-11-12 22:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resources_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PubType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publicationType', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='PaperTemp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('link', models.URLField(blank=True, null=True)),
                ('publicationType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resources_app.pubtype')),
            ],
        ),
    ]
