# Generated by Django 4.2.6 on 2023-11-18 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources_app', '0002_pubtype_papertemp'),
    ]

    operations = [
        migrations.AddField(
            model_name='papertemp',
            name='authors',
            field=models.ManyToManyField(to='resources_app.author'),
        ),
        migrations.AddField(
            model_name='papertemp',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='resources/'),
        ),
    ]
