# Generated by Django 4.2.6 on 2023-11-18 23:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resources_app', '0003_papertemp_authors_papertemp_thumbnail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='affiliation',
        ),
        migrations.RemoveField(
            model_name='author',
            name='email',
        ),
    ]
