# Generated by Django 4.2.6 on 2023-10-31 23:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('community_app', '0002_participant_image_participant_roll_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Roll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='participant',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='participant',
            name='contact',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.RemoveField(
            model_name='participant',
            name='institution',
        ),
        migrations.AlterField(
            model_name='participant',
            name='tags',
            field=models.ManyToManyField(blank=True, to='community_app.tag'),
        ),
        migrations.AddField(
            model_name='participant',
            name='institution',
            field=models.ManyToManyField(blank=True, to='community_app.institution'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='roll',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='community_app.roll'),
        ),
    ]
