# Generated by Django 4.2.6 on 2023-10-31 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community_app', '0003_roll_participant_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='contact',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
