# Generated by Django 4.2.6 on 2023-10-31 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community_app', '0004_alter_participant_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='contact',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='participant',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='participant',
            name='institution',
            field=models.ManyToManyField(blank=True, null=True, to='community_app.institution'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='tags',
            field=models.ManyToManyField(blank=True, null=True, to='community_app.tag'),
        ),
    ]
