# Generated by Django 4.2.6 on 2023-11-04 15:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('community_app', '0005_alter_participant_contact_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='fiield',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='community_app.studyfield'),
        ),
    ]
