# Generated by Django 4.2.6 on 2023-11-04 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community_app', '0006_participant_fiield'),
    ]

    operations = [
        migrations.RenameField(
            model_name='participant',
            old_name='fiield',
            new_name='field',
        ),
    ]
