# Generated by Django 4.2.6 on 2023-11-04 19:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('community_app', '0007_rename_fiield_participant_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='roll',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='community_app.roll'),
        ),
    ]
