# Generated by Django 4.2.6 on 2023-11-04 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community_app', '0008_alter_participant_roll'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='image',
            field=models.ImageField(default='/static/psesyn/images/community/default.png', upload_to='participants/'),
        ),
    ]
