# Generated by Django 4.2.6 on 2023-11-04 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community_app', '0010_alter_participant_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='image',
            field=models.ImageField(blank=True, default='/defaults/default.png', upload_to='participants/'),
        ),
    ]
