# Generated by Django 4.2.6 on 2023-11-24 09:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('community_app', '0012_alter_participant_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Roll_s',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='participant',
            name='roll_s',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='community_app.roll_s'),
        ),
    ]
